"""NCBI genetic-code table names and ids.

@generated by codegen/generate_tables.py -- DO NOT EDIT BY HAND.
Source of truth: BioPython 1.87.
"""

from __future__ import annotations

TABLE_IDS: frozenset[int] = frozenset([1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

"""Every accepted table name/alias, lower-cased, mapped to its NCBI id."""
NAME_TO_ID: dict[str, int] = {
    'standard': 1,
    'sgc0': 1,
    'vertebrate mitochondrial': 2,
    'sgc1': 2,
    'yeast mitochondrial': 3,
    'sgc2': 3,
    'mold mitochondrial': 4,
    'protozoan mitochondrial': 4,
    'coelenterate mitochondrial': 4,
    'mycoplasma': 4,
    'spiroplasma': 4,
    'sgc3': 4,
    'invertebrate mitochondrial': 5,
    'sgc4': 5,
    'ciliate nuclear': 6,
    'dasycladacean nuclear': 6,
    'hexamita nuclear': 6,
    'sgc5': 6,
    'echinoderm mitochondrial': 9,
    'flatworm mitochondrial': 9,
    'sgc8': 9,
    'euplotid nuclear': 10,
    'sgc9': 10,
    'bacterial': 11,
    'archaeal': 11,
    'plant plastid': 11,
    'alternative yeast nuclear': 12,
    'ascidian mitochondrial': 13,
    'alternative flatworm mitochondrial': 14,
    'blepharisma macronuclear': 15,
    'chlorophycean mitochondrial': 16,
    'trematode mitochondrial': 21,
    'scenedesmus obliquus mitochondrial': 22,
    'thraustochytrium mitochondrial': 23,
    'pterobranchia mitochondrial': 24,
    'candidate division sr1': 25,
    'gracilibacteria': 25,
    'pachysolen tannophilus nuclear': 26,
    'karyorelict nuclear': 27,
    'condylostoma nuclear': 28,
    'mesodinium nuclear': 29,
    'peritrich nuclear': 30,
    'blastocrithidia nuclear': 31,
    'balanophoraceae plastid': 32,
    'cephalodiscidae mitochondrial': 33,
}

"""Primary display name per id."""
ID_TO_NAME: dict[int, str] = {
    1: 'Standard',
    2: 'Vertebrate Mitochondrial',
    3: 'Yeast Mitochondrial',
    4: 'Mold Mitochondrial',
    5: 'Invertebrate Mitochondrial',
    6: 'Ciliate Nuclear',
    9: 'Echinoderm Mitochondrial',
    10: 'Euplotid Nuclear',
    11: 'Bacterial',
    12: 'Alternative Yeast Nuclear',
    13: 'Ascidian Mitochondrial',
    14: 'Alternative Flatworm Mitochondrial',
    15: 'Blepharisma Macronuclear',
    16: 'Chlorophycean Mitochondrial',
    21: 'Trematode Mitochondrial',
    22: 'Scenedesmus obliquus Mitochondrial',
    23: 'Thraustochytrium Mitochondrial',
    24: 'Pterobranchia Mitochondrial',
    25: 'Candidate Division SR1',
    26: 'Pachysolen tannophilus Nuclear',
    27: 'Karyorelict Nuclear',
    28: 'Condylostoma Nuclear',
    29: 'Mesodinium Nuclear',
    30: 'Peritrich Nuclear',
    31: 'Blastocrithidia Nuclear',
    32: 'Balanophoraceae Plastid',
    33: 'Cephalodiscidae Mitochondrial',
}

"""Tables with codons that are both a stop and an amino acid (NCBI 27/28/31)."""
DUAL_CODING: dict[int, tuple[str, ...]] = {
    27: ('TGA',),
    28: ('TAA', 'TAG', 'TGA'),
    31: ('TAA', 'TAG'),
}
